# Generated by Django 2.2.13 on 2022-02-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content1', models.TextField(verbose_name='about me sections 1')),
                ('content2', models.TextField(verbose_name='about me sections 2')),
                ('content3', models.TextField(verbose_name='about me sections 3')),
            ],
        ),
    ]
