# Generated by Django 2.2.13 on 2022-02-10 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porto', '0003_auto_20220210_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='about',
        ),
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
