# Generated by Django 2.2.13 on 2022-02-10 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porto', '0007_category_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
