# Generated by Django 2.2.13 on 2022-02-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porto', '0008_auto_20220210_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Title Services')),
                ('content', models.CharField(max_length=250, verbose_name='Content Services')),
                ('cart1Title', models.CharField(max_length=25, verbose_name='Cart One Title')),
                ('cart1Content', models.CharField(max_length=100, verbose_name='Cart One Content')),
                ('cart2Title', models.CharField(max_length=25, verbose_name='Cart Two Title')),
                ('cart2Content', models.CharField(max_length=100, verbose_name='Cart Two Content')),
                ('cart3Title', models.CharField(max_length=25, verbose_name='Cart Three Title ')),
                ('cart3Content', models.CharField(max_length=100, verbose_name='Cart Three Content')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
