# Generated by Django 2.2.13 on 2022-02-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porto', '0011_delete_portofilo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='portfolio/')),
                ('link', models.URLField()),
            ],
        ),
    ]
