# Generated by Django 2.2.13 on 2022-02-12 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porto', '0012_portfolio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
