# Generated by Django 2.2.13 on 2022-02-13 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porto', '0014_portofilos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portofilos',
        ),
    ]
