# Generated by Django 2.2.13 on 2022-02-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porto', '0015_delete_portofilos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portofilos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Title Portfolio')),
                ('pictures', models.FileField(upload_to='portofilo/', verbose_name='Portfolio Image')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
