# Generated by Django 2.2.13 on 2022-02-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porto', '0017_delete_portofilos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='portfolio/')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
            ],
        ),
    ]
